M48
; DRILL file KiCad 10.0.2 date 2026-07-03T11:27:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-03T11:27:59+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X154.0Y-83.0
T2
X141.3Y-90.0
X154.0Y-90.0
T3
X125.0Y-87.73
X125.0Y-90.27
M30
